config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :charges
  resources :suppliers
  resources :posts do
    resources :comments
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end 
  get 'admin/index', to: 'admin#index'
  root 'pages#index'
  get 'contact', to: 'contact#index'
  post 'contact', to: 'contact#mail'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
    before_action :set_current_message, only: [:create]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.user_id = current_user.id

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    def set_current_message
      @message = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:user_id, :title, :content)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= simple_form_for(@message) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="user-name-message">
        <%#= f.label :user_name %>
        <%#= f.text_field :user_name %>
    </div>
    <%= f.input :title %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages & Event</h1>
<br>
  <div class="row">
    <% @messages.reverse[0..9].each do |message| %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <div class="caption">
        <strong>Poster id:</strong>
          <%= message.user_id %><br>
          <!-- <strong>Poster:</strong>
            <%#= message.user_name %><br> -->
        <strong>title:</strong>
          <%= message.title %><br>
        <strong>Content:</strong>
        <%= message.content %><br>
        <%= link_to 'Show', message %> |
        <!-- <#% if user_signed_in? %>
            <#% if current_user.user_id? %> -->
        <%= link_to 'Edit', edit_message_path(message) %> |
        <%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %>
            <!-- <#% end %>
        <#% end %> -->
        <br>
     </div>
   </div>
 </div>
   <% end %>
</div>
<br>
<br>
<%= link_to 'New Message', new_message_path %> |
<%= link_to 'Top page', root_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %> |
<%= link_to 'Top page', root_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Poster id:</strong>
  <%= @message.user_id %>
</p>

<!-- <p>
  <strong>Poster:</strong>
  <%#= @message.user_name%>
</p> -->

<p>
  <strong>Title:</strong>
  <%= @message.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %> |
<%= link_to 'Top page', root_path %>