config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :charges
  resources :suppliers
  resources :posts do
    resources :comments
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end 
  get 'admin/index', to: 'admin#index'
  root 'pages#index'
  get 'contact', to: 'contact#index'
  post 'contact', to: 'contact#mail'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  mount_uploaders :images, AvatarUploader
  serialize :images, JSON # If you use SQLite, add this line.
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/page.rb
class Page < ApplicationRecord

  mount_uploaders :images, AvatarUploader
  serialize :images, JSON # If you use SQLite, add this line.

  end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  #testing
   validates :item_name, presence: true, length: { minimum: 2 }

  mount_uploaders :images, AvatarUploader
  serialize :images, JSON # If you use SQLite, add this line.
  # scope :approved, -> { where(approved: true) }
  # scope :pending, -> { where(approved: false) }


end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  after_create :assign_default_role

 def assign_default_role
   self.add_role(:member) if self.roles.blank?
 end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  has_many :posts
  has_many :comments
  has_one :supplier
  has_many :messages

  # def admin?
  #   has_role?(:admin)
  # end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      #user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  class User < ApplicationRecord
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end


end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authorize_user, only: :index
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]
  before_action :set_current_supplier, only: [:show, :edit, :update, :destroy, :create]
  before_action :set_current_user, only: [:show, :edit, :update, :destroy, :create]


  def index
    @supplier = Supplier.new
    @suppliers = Supplier.all
    @user = User.new
    @usera = User.all
    @post = Post.new
    @posts = Post.all
  end

    private

  def authorize_user
    #  if current_user.user_type != 'admin'
      if current_user.has_role?(:admin) == false
      redirect_to root_path, notice: 'Login as User'
    end
  end


  def set_supplier
    @supplier = Supplier.find(params[:id])
  end
  def supplier_params
    params.require(:supplier).permit(:supplier_name, :supplier_phone_number, :company_number, :verified)
  end


  def set_current_supplier
    @user = current_user
  end
  def post_params
    params.require(:post).permit(:item_name, :item_description, :supplier_name, :supplier_description, :user_id, {images: []})
  end


  def set_current_user
    @user = current_user
  end
  def comment_params
    params.require(:comment).permit(:user_id, :title, :content, :post_id, :user_name, {images: []})
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @post = Post.new
    @posts = Post.all
    @comment = Comment.new
    # @post = Post.new.images
  end

  def create

  end

  def post_params
    params.require(:post).permit(:item_name, {images: []})
  end

  def post_params
    params.require(:post).permit(:item_name, :item_description, :supplier_name, :supplier_description, :user_id, {images: []})
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_current_supplier, only: [:show, :edit, :update, :destroy, :create]


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @q = Post.ransack(params[:q])
    @posts = @q.result    #(distinct: true)
  end



  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = Comment.all
    @comments = @post.comments
    @comment = Comment.new
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
    @comment = Comment.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @comment = Comment.new

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    authorize @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_current_supplier
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:item_name, :item_description, :supplier_name, :supplier_description, :user_id, {images: []}, :user_name, :title, :content, :comment)
    # params.require(:post).permit(policy(@post).permitted_attributes
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/admin/index.html.erb
<h1>Admin page</h1>
<br>
<% @suppliers.reverse.each do |supplier| %>
    Supplier name : <%= supplier.supplier_name %><br>
    Resistered email: <%= supplier.email %><br>
    Supplier id : <%= supplier.user.email %><br>
    Supplier phone number : <%= supplier.supplier_phone_number %><br>
    Supplier company number : <%= supplier.company_number %><br>
    Verified : <%= supplier.verified %><br>
    <%= link_to 'Show', supplier %> |

    <% if user_signed_in? %>
      <% if current_user.has_role? :admin %>
         <%= link_to 'Edit', edit_supplier_path(supplier) %> |
      <% end %>
    <% end %>

    <%= link_to 'Destroy', supplier, method: :delete, data: { confirm: 'Are you sure?' } %>
    <br>
    <br>
  </tr>
<% end %>

<br>

<% @posts.reverse.each do |post| %>
    Item name :<%= post.item_name %><br>
    Item description :<%= post.item_description %><br>
    Supplier name :<%= post.supplier_name %><br>
    Supplier description :<%= post.supplier_description %><br>
    User id :<%= post.user.email %><br>
   <%= link_to 'Show', post %> |
   <%= link_to 'Edit', edit_post_path(post) %> |
   <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %><br>
   <br>
<% end %>

<br>

<%= link_to "Top page", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fairenough2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%#= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<%= render 'partials/nav' %>
<p id="notice"><%= notice %></p>

<div class = "fairtrade_fairenough">
  <img src="https://image.ibb.co/fNvzqk/githublogofe.png" width="600" />
</div>
   <!-- </div>
</div> -->


<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail-1">
      <img src="https://images.pexels.com/photos/2128/person-woman-sitting-old.jpg?w=1260&h=750&auto=compress&cs=tinysrgb" alt="about-ft" height="300">
      <div class="caption">
        <h3>Poverty</h3>
        <h4>900 million people living with USD 1.9/day</h4>
        <h4>20 billion farmer are less paid</h4>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail-2">
      <img src="https://images.pexels.com/photos/13918/pexels-photo-13918.jpeg?w=1260&h=750&auto=compress&cs=tinysrgb" alt="about-ft" height="300">
      <div class="caption">
        <h3>Fair trade</h3>
        <h4>A fair treatment for farmers</h4>
        <h4>Selling Items with fair price</h4>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail-3">
      <img src="https://images.pexels.com/photos/95425/pexels-photo-95425.jpeg?w=1260&h=750&auto=compress&cs=tinysrgb" alt="about-ft" height="300">
      <div class="caption">
        <h3>Let's join</h3>
        <h4>AUD 10 billion annual turnover in global</h4>
        <h4>74 countries, 1.5 million people</h4>
      </div>
    </div>
  </div>
</div>


<br>
<br>

<h2>New arrival Items</h2>
<br>
<div class="row">
<% @posts.reverse[0..3].each do |post| %>
	<div class="col-xs-6 col-md-3">
		<div class="thumbnail">
      <% post.images.each do |image| %>
          <img src ="<%= image %>" alt="Image">
        <% end %>
        <!-- <#%= post.inspect %> -->
			<div class="caption">
				<h4><%= post.item_name %><h4>
        <br>
        <%= link_to "See more", post_path(post.id) %>
        <br><br>
        <%= render 'partials/stripe', post: post %>
        <!-- <div class="btn-group" data-toggle="buttons-checkbox">
          <button type="button" class="btn btn-primary-see-more"><%= link_to "See more", post_path(post.id) %></button>
          <button type="button" class="btn btn-primary-purchase">Purchase</button>
        </div> -->
			</div>
		</div>
	</div>
    <% end %>
</div>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <class="navbar-brand-logo">
        <%#= image_tag 'imagfairenoughlogo.png', class:"imagfairenoughlogo" %>
     </div>
    

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <% if user_signed_in? %>
         <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
         <li><%= link_to 'Login', new_user_session_path  %></li>
        <% end %>

        <li><a href="users/edit">Profile</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Texile</a></li>
            <li><a href="#">Food</a></li>
            <li><a href="#">Cotton</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Individual customer</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Corporate customer</a></li>
          </ul>
        </li>
        <li><a href="messages">Message</a></li>
        <li><a href="contact">Contact</a></li>

        <% if user_signed_in? %>
          <% if !current_user.supplier.present? %>
            <li>
              <%= link_to 'Registar as Supplier', new_supplier_path %>
            </li>
          <% end %>
        <% end %>

          <% if user_signed_in? %>
          <!-- signedin -->
            <% if current_user.supplier.present? %>
            <!-- present -->
            <%#= current_user.supplier.inspect %>
              <% if current_user.supplier.verified %>
                 <li><%= link_to 'Post new item', new_post_path %></li>
              <% end %>
            <% end %>
          <% end %>
          <% if user_signed_in? %>
            <% if current_user.has_role? :admin %>
              <li><%= link_to 'Post new item', new_post_path %></li>
            <% end %>
          <% end %>

          <% if user_signed_in? %>
          <% if current_user.has_role? :admin %>
            <li><%= link_to 'Admin', admin_index_path %></li>
          <% end %>
          <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_stripe.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Payment for: <%= post.title %>"
          data-amount="500"
          data-locale="auto"></script>

<% end %>