config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :charges
  resources :suppliers
  resources :posts do
    resources :comments
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end 
  get 'admin/index', to: 'admin#index'
  root 'pages#index'
  get 'contact', to: 'contact#index'
  post 'contact', to: 'contact#mail'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :user
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]
  before_action :current_supplier, only: [:create]

  # GET /suppliers
  # GET /suppliers.json
  def index
    @suppliers = Supplier.all
  end

  # GET /suppliers/1
  # GET /suppliers/1.json
  def show
  end

  # GET /suppliers/new
  def new
    @supplier = Supplier.new
  end

  # GET /suppliers/1/edit
  def edit
  end

  # POST /suppliers
  # POST /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)
    @supplier.user_id = current_user.id

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to @supplier, notice: 'Supplier was successfully created.' }
        format.json { render :show, status: :created, location: @supplier }
      else
        format.html { render :new }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1
  # PATCH/PUT /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to @supplier, notice: 'Supplier was successfully updated.' }
        format.json { render :show, status: :ok, location: @supplier }
      else
        format.html { render :edit }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1
  # DELETE /suppliers/1.json
  def destroy
    @supplier.destroy
    respond_to do |format|
      format.html { redirect_to suppliers_url, notice: 'Supplier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    def current_supplier
      @supplier = current_user
    end

    # def set_current_user
    #   @user = current_user
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplier_params
      params.require(:supplier).permit(:supplier_name, :supplier_phone_number, :company_number, :verified, :email, :supplier_id, :user_id)
    end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_form.html.erb
<%= form_for(supplier) do |f| %>
  <% if supplier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(supplier.errors.count, "error") %> prohibited this supplier from being saved:</h2>

      <ul>
      <% supplier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :supplier_name %>
    <%= f.text_field :supplier_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :supplier_phone_number %>
    <%= f.text_field :supplier_phone_number %>
  </div>

  <div class="field">
    <%= f.label :company_number %>
    <%= f.text_field :company_number %>
  </div>

  <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
       <div class="field">
         <%= f.label :verified %>
         <%= f.check_box :verified %>
       </div>
    <% end %>
  <% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1>Editing Supplier</h1>

<%= render 'form', supplier: @supplier %>

<%= link_to 'Show', @supplier %> |
<%= link_to 'Back', suppliers_path %>

app/views/suppliers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Suppliers</h1>

    <% @suppliers.reverse.each do |supplier| %>
        Supplier name : <%= supplier.supplier_name %><br>
        Supplier phone number : <%= supplier.supplier_phone_number %><br>
        Supplier company number : <%= supplier.company_number %><br>
        Verified : <%= supplier.verified %><br>
        <%= link_to 'Show', supplier %> |
        <%#= link_to 'Edit', edit_supplier_path(supplier) %>
        <%= link_to 'Destroy', supplier, method: :delete, data: { confirm: 'Are you sure?' } %>
        <br>
        <br>
      </tr>
    <% end %>

<br>

<% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
     <%= link_to 'Admin index', admin_index_path %> |
     <%= link_to 'New Supplier', new_supplier_path %>
  <% else %>
     <%= link_to 'New Supplier', new_supplier_path %>
  <% end %>
<% end %>

app/views/suppliers/new.html.erb
<h1>New Supplier</h1>

<%= render 'form', supplier: @supplier %>

 <%= link_to 'Top page',  root_path %>
<br>
<br>

app/views/suppliers/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Supplier Profile</h3>
<br>

<p>
  <strong>Supplier name:</strong>
  <%= @supplier.supplier_name %>
</p>

<p>
  <strong>Supplier phone number:</strong>
  <%= @supplier.supplier_phone_number %>
</p>

<p>
  <strong>Company number:</strong>
  <%= @supplier.company_number %>
</p>

<% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
    <p>
    <strong>Verified:</strong>
      <%= @supplier.verified %>
    </p>
  <% end %>
<% end %>

<% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
     <%= link_to 'Admin index', admin_index_path %> |
     <%= link_to 'Top page',  root_path %>
  <% else%>
     <%= link_to 'Back', suppliers_path %> |
     <%= link_to 'Toppage',  root_path %>
  <% end %>
<% end %>